[package]
name = "basalt"
edition = "2018"
version = "0.13.0"
authors = ["Austin <me@austinj.me>"]
repository = "https://github.com/AustinJ235/basalt"
documentation = "https://docs.rs/basalt"
description = "A window/ui framework built upon vulkan."
license = "MIT"
keywords = ["vulkan", "graphics", "gui", "framework", "interface"]
categories = ["graphics","gui"]
readme = "README.md"

[dependencies]
vulkano = "^0.27.1"
vulkano-shaders = "^0.27.1"
ilmenite = "0.8.0"
image = "0.23.14"
parking_lot = "0.11.2"
crossbeam = "0.8.1"
num_cpus = "1.13.0"
winit = "0.26.0"
curl = "0.4.41"
ordered-float = "2.8.0"
arc-swap = "1.5.0"
