[package]
name = "examples"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../basalt" }
basalt-common = { path = "../basalt-common" }
basalt-macros = { path = "../basalt-macros" }
once_cell = "1.8.0"
vulkano = "^0.27.1"
vulkano-shaders = "^0.27.1"
