[package]
name = "examples"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../" }
once_cell = "1.3.1"
vulkano = { path = "../../vulkano/vulkano", version = "0.23" }
vulkano-shaders = { path = "../../vulkano/vulkano-shaders", version = "0.23" }
