[package]
name = "examples"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../" }
once_cell = "1.3.1"
vulkano = "0.24"
vulkano-shaders = "0.24"
