[package]
name = "examples"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../" }
once_cell = "1.3.1"
vulkano = { git = "https://github.com/AustinJ235/vulkano.git", branch = "basalt" }
vulkano-shaders = { git = "https://github.com/AustinJ235/vulkano.git", branch = "basalt" }
