[package]
name = "examples"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../" }
once_cell = "1.8.0"
vulkano = { path = "../../vulkano/vulkano" }
vulkano-shaders = { path = "../../vulkano/vulkano-shaders" }
