[package]
name = "examples"
edition = "2021"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../" }
# Dependancies below are not required for app.rs
vulkano = "0.33"
vulkano-shaders = "0.33"
