name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows_stable:
    runs-on: [self-hosted, Windows]
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: cargo update
    - name: Build
      run: cargo build --verbose
