name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows_stable:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ninja Install
      run: pip install ninja
    - name: Rustup Install Nightly
      run: rustup toolchain install nightly
    - name: Rustup Set Default
      run: rustup default nightly
    - name: Rustup Update
      run: rustup update
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
